name: autorelease

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current tag
        id: currenttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Check new Unleashed release
        run: |
          UNLEASHED_TAG=$(curl -sL https://api.github.com/repos/DarkFlippers/unleashed-firmware/releases/latest | jq -r ".tag_name")
          if [[ "${{ steps.currenttag.outputs.tag }}" == "$UNLEASHED_TAG" ]]; then exit 1; fi
          echo "CURRENT_UNLEASHED_TAG=$UNLEASHED_TAG" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: an4tur0r
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            an4tur0r/flipperzero-unleashed:${{ env.CURRENT_UNLEASHED_TAG }}, an4tur0r/flipperzero-unleashed:latest
          build-args: |
            REF_TAG=${{ env.CURRENT_UNLEASHED_TAG }}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.CURRENT_UNLEASHED_TAG }}
